### PR TITLE
feat: adds option to set default statusCode

### PR DESCRIPTION
**Pull request by derz**
Adds statusCode field in options to set default for all rules:

`
		[
			'@nuxtjs/redirect-module',
			{
				rules: [],
				statusCode: 301
			}
		]`

### CODE REVIEW

**Comment by manniL** [comment]
Thanks for the PR! Could you add a test covering the changes?

**Comment by derz** [comment]
@manniL added tests in latest commit. Let me know, if anything is missing :-)

**Comment by manniL** [comment]
Thank you!

**Comment by derz** [comment]
any chance you could create a new release @manniL (or is it already planned?)? Thank you :-)

**Comment by manniL** [comment]
Sure, it's coming :relaxed:

**Pull request merged**
